spring:
  datasource:
    url: jdbc:mysql://localhost:3306/test2?useSSL=false
    username: 
    password: 
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    properties:
      hibernate:
        hbm2ddl:
          auto: update
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
    show-sql: true
  mail:
      host: 
      username: 
      password: 
      properties:
          mail:
              smtp:
                  auth: true
                  ssl:
                      enable: true

